name: flutter_numeric_text
description: "This widget allows you to animate any text. The widget is easy to use and allows you to seamlessly replace Text(data) with NumericText(data)."
version: 1.3.3
homepage: https://github.com/strash/flutter_numeric_text
repository: https://github.com/strash/flutter_numeric_text

topics:
  - widget
  - ui
  - animation
  - text

environment:
  sdk: ">=3.6.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
