name: flutter_numeric_text
description: "This widget allows you to animate text."
version: 1.1.0
homepage: https://github.com/strash/flutter_numeric_text
repository: https://github.com/strash/flutter_numeric_text

topics:
  - widget
  - ui
  - animation
  - text

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
